[package]
name = "blackbox_cast_codegen"
version = "0.1.0"
edition = "2021"
description = "Trait cast library"
keywords = [ "blackbox", "blackbox_di", "blackbox_cast", "trait", "cast"]
repository = "https://github.com/MichailShcherbakov/blackbox_di"
homepage = "https://github.com/MichailShcherbakov/blackbox_di"
license = "MIT"
readme = "../../../../README.md"
authors = [ "MichailShcherbakov <MichailShcherbakov@gmail.com>" ]

[dependencies]
proc-macro2 = "1.0.50"
quote = "1.0.23"
syn = { version = "1.0.107", features = [ "full", "extra-traits" ] }
uuid = { version = "1.2.2", features = ["v4", "fast-rng"] }

[lib]
proc-macro = true