[package]
name = "blackbox_cast"
version = "0.1.1"
edition = "2021"
description = "Trait cast library"
keywords = [ "blackbox", "blackbox_di", "blackbox_cast", "trait", "cast"]
repository = "https://github.com/MichailShcherbakov/blackbox_di"
homepage = "https://github.com/MichailShcherbakov/blackbox_di"
license = "MIT"
readme = "../../README.md"
authors = [ "MichailShcherbakov <MichailShcherbakov@gmail.com>" ]

[dependencies]
blackbox_cast_codegen = { path = "./packages/cast_codegen", version = "0.1.1" }
once_cell = "1.17.0"
linkme = "0.3.7"