[package]
name = "cast"
version = "0.1.0"
edition = "2021"
description = "Trait cast library"
keywords = [ "blackbox", "blackbox_di", "blackbox_di cast", "traitcast", "upcast", "trait", "cast"]
repository = "https://github.com/MichailShcherbakov/blackbox_di"
homepage = "https://github.com/MichailShcherbakov/blackbox_di"
license = "MIT"
readme = "README.md"
authors = [ "50011226+MichailShcherbakov@users.noreply.github.com" ]

[dependencies]
async-trait = "0.1.61"
once_cell = "1.17.0"
linkme = "0.3.7"

[dependencies.cast_codegen]
path = "./packages/cast_codegen"
version = "0.1.0"