[package]
name = "blackbox_core_codegen"
version = "0.1.1"
edition = "2021"
description = "Rust dependency injection library"
keywords = [ "blackbox_di", "dependency-injection", "inversion-of-control", "di", "ioc"]
repository = "https://github.com/MichailShcherbakov/blackbox_di"
homepage = "https://github.com/MichailShcherbakov/blackbox_di"
license = "MIT"
readme = "../../../../README.md"
authors = [ "MichailShcherbakov <MichailShcherbakov@gmail.com>" ]

[dependencies]
proc-macro2 = "1.0.50"
quote = "1.0.23"
syn = { version = "1.0.107", features = [ "full", "extra-traits" ] }

[lib]
proc-macro = true
doctest = false